In [316]:
import pandas as pd

In [317]:
data_set= pd.read_csv('Phones.csv',index_col=0)
data_set.head()

Name    Brand                   Model  \
0  OnePlus 7T Pro McLaren Edition  OnePlus  7T Pro McLaren Edition   
1                   Realme X2 Pro   Realme                  X2 Pro   
2               iPhone 11 Pro Max    Apple       iPhone 11 Pro Max   
3                       iPhone 11    Apple               iPhone 11   
4                    LG G8X ThinQ       LG               G8X ThinQ   

   Battery capacity (mAh)  Screen size (inches) Touchscreen  Resolution x  \
0                    4085                  6.67         Yes          1440   
1                    4000                  6.50         Yes          1080   
2                    3969                  6.50         Yes          1242   
3                    3110                  6.10         Yes           828   
4                    4000                  6.40         Yes          1080   

   Resolution y  Processor  RAM (MB)  ...  Rear camera  Front camera  \
0          3120          8     12000  ...         48.0          16.0   
1          2400          8      6000  ...         64.0          16.0   
2          2688          6      4000  ...         12.0          12.0   
3          1792          6      4000  ...         12.0          12.0   
4          2340          8      6000  ...         12.0          32.0   

   Operating system Wi-Fi Bluetooth  GPS Number of SIMs   3G 4G/ LTE   Price  
0           Android   Yes       Yes  Yes              2  Yes     Yes   58998  
1           Android   Yes       Yes  Yes              2  Yes     Yes   27999  
2               iOS   Yes       Yes  Yes              2  Yes     Yes  106900  
3               iOS   Yes       Yes  Yes              2  Yes     Yes   62900  
4           Android   Yes       Yes  Yes              1   No      No   49990  

[5 rows x 21 columns]

In [ ]:
# ADD THIS NEW BLOCK
import numpy as np

# Find brands that appear less than 15 times in the dataset
brand_counts = data_set['Brand'].value_counts()
brands_to_group = brand_counts[brand_counts < 15].index

# Replace these rare brands with the label 'Other'
data_set.loc[data_set['Brand'].isin(brands_to_group), 'Brand'] = 'Other'

print("This is the new, cleaned distribution of brands:")
print(data_set['Brand'].value_counts())

In [318]:

print(data_set.columns)

Index(['Name', 'Brand', 'Model', 'Battery capacity (mAh)',
       'Screen size (inches)', 'Touchscreen', 'Resolution x', 'Resolution y',
       'Processor', 'RAM (MB)', 'Internal storage (GB)', 'Rear camera',
       'Front camera', 'Operating system', 'Wi-Fi', 'Bluetooth', 'GPS',
       'Number of SIMs', '3G', '4G/ LTE', 'Price'],
      dtype='object')


In [319]:
data_set.drop('Touchscreen', axis=1, inplace=True)

In [320]:
CTD=['Wi-Fi', 'Bluetooth', 'GPS','3G', '4G/ LTE']
data_set.drop(CTD, axis=1, inplace=True)

In [321]:
data_set.head()

Name    Brand                   Model  \
0  OnePlus 7T Pro McLaren Edition  OnePlus  7T Pro McLaren Edition   
1                   Realme X2 Pro   Realme                  X2 Pro   
2               iPhone 11 Pro Max    Apple       iPhone 11 Pro Max   
3                       iPhone 11    Apple               iPhone 11   
4                    LG G8X ThinQ       LG               G8X ThinQ   

   Battery capacity (mAh)  Screen size (inches)  Resolution x  Resolution y  \
0                    4085                  6.67          1440          3120   
1                    4000                  6.50          1080          2400   
2                    3969                  6.50          1242          2688   
3                    3110                  6.10           828          1792   
4                    4000                  6.40          1080          2340   

   Processor  RAM (MB)  Internal storage (GB)  Rear camera  Front camera  \
0          8     12000                  256.0         48.0          16.0   
1          8      6000                   64.0         64.0          16.0   
2          6      4000                   64.0         12.0          12.0   
3          6      4000                   64.0         12.0          12.0   
4          8      6000                  128.0         12.0          32.0   

  Operating system  Number of SIMs   Price  
0          Android               2   58998  
1          Android               2   27999  
2              iOS               2  106900  
3              iOS               2   62900  
4          Android               1   49990

In [322]:
print(data_set.columns)

Index(['Name', 'Brand', 'Model', 'Battery capacity (mAh)',
       'Screen size (inches)', 'Resolution x', 'Resolution y', 'Processor',
       'RAM (MB)', 'Internal storage (GB)', 'Rear camera', 'Front camera',
       'Operating system', 'Number of SIMs', 'Price'],
      dtype='object')


In [323]:
print(data_set.isnull().sum())

Name                      0
Brand                     0
Model                     0
Battery capacity (mAh)    0
Screen size (inches)      0
Resolution x              0
Resolution y              0
Processor                 0
RAM (MB)                  0
Internal storage (GB)     0
Rear camera               0
Front camera              0
Operating system          0
Number of SIMs            0
Price                     0
dtype: int64


In [324]:
# Check the distribution of brands in your dataset
print(data_set['Brand'].value_counts())

Brand
Intex        117
Samsung      101
Micromax      71
Lava          59
Panasonic     55
            ... 
Onida          1
Aqua           1
Jio            1
Razer          1
Philips        1
Name: count, Length: 76, dtype: int64


New brand distribution after grouping:
Brand
Intex         117
Other         112
Samsung       101
Micromax       71
Lava           59
Panasonic      55
Vivo           52
Xiaomi         47
Motorola       42
LG             42
Lenovo         42
Asus           37
HTC            35
Nokia          35
Oppo           35
Karbonn        34
Honor          33
Lyf            33
Gionee         33
Sony           28
Xolo           25
InFocus        19
Coolpad        19
Swipe          18
Realme         18
BlackBerry     17
Infinix        17
Apple          17
Tecno          16
iVoomi         16
Itel           15
iBall          14
Videocon       13
Yu             13
Zopo           12
Huawei         12
Nubia          12
OnePlus        12
Zen            11
Google         10
Alcatel        10
Name: count, dtype: int64


In [326]:
# Check the distribution of brands in your dataset
print(data_set['Brand'].value_counts())

Brand
Intex         117
Other         112
Samsung       101
Micromax       71
Lava           59
Panasonic      55
Vivo           52
Xiaomi         47
Motorola       42
LG             42
Lenovo         42
Asus           37
HTC            35
Nokia          35
Oppo           35
Karbonn        34
Honor          33
Lyf            33
Gionee         33
Sony           28
Xolo           25
InFocus        19
Coolpad        19
Swipe          18
Realme         18
BlackBerry     17
Infinix        17
Apple          17
Tecno          16
iVoomi         16
Itel           15
iBall          14
Videocon       13
Yu             13
Zopo           12
Huawei         12
Nubia          12
OnePlus        12
Zen            11
Google         10
Alcatel        10
Name: count, dtype: int64


In [327]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

le =  LabelEncoder()


In [328]:
to_be_encoded=['Name','Brand', 'Model','Operating system']
for col in to_be_encoded:
    data_set[col] = le.fit_transform(data_set[col])

In [329]:
data_set.head()

Name  Brand  Model  Battery capacity (mAh)  Screen size (inches)  \
0   842     23     49                    4085                  6.67   
1   959     27   1142                    4000                  6.50   
2  1341      1   1288                    3969                  6.50   
3  1339      1   1286                    3110                  6.10   
4   481     15    522                    4000                  6.40   

   Resolution x  Resolution y  Processor  RAM (MB)  Internal storage (GB)  \
0          1440          3120          8     12000                  256.0   
1          1080          2400          8      6000                   64.0   
2          1242          2688          6      4000                   64.0   
3           828          1792          6      4000                   64.0   
4          1080          2340          8      6000                  128.0   

   Rear camera  Front camera  Operating system  Number of SIMs   Price  
0         48.0          16.0                 0               2   58998  
1         64.0          16.0                 0               2   27999  
2         12.0          12.0                 6               2  106900  
3         12.0          12.0                 6               2   62900  
4         12.0          32.0                 0               1   49990

In [330]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [331]:
X = data_set[[ "Screen size (inches)", "Operating system", "RAM (MB)", "Internal storage (GB)", "Battery capacity (mAh)", "Front camera", "Rear camera", "Price", "Number of SIMs", "Resolution x", "Resolution y", "Processor"]]

In [332]:
Y = data_set["Brand"]

In [333]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(951, 12) (408, 12) (951,) (408,)


In [334]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [335]:
print(y_train.shape)
print(X_train.shape)

(951,)
(951, 12)


In [ ]:
from sklearn.tree import DecisionTreeClassifier

# 1. Initialize the Decision Tree model
model = DecisionTreeClassifier(random_state=42)

# 2. Train the model on your scaled training data
model.fit(X_train, y_train)

# 3. Make predictions on the test data
# model

RandomForestClassifier(random_state=42)

In [337]:
y_pred = model.predict(X_test)

In [338]:
from sklearn import metrics

cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)

accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)




[[0 0 0 ... 0 0 0]
 [0 6 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
Accuracy score: 0.2818627450980392
